Ability to set mobile view cookie name in root web.config
dnnsoftware/Dnn.Platform pull request #4064
Opened 2020-09-08 05:02 UTC by thabaum

Fixes #4044 
## Summary

Allows ability to set mobile view cookie name.

I have been having issues with VS + Github so may need new setup to get that part right... please double check things for me if you can test the cookies are able to be set properly when this fix is applied.  0 build errors... but still something can go wrong for someone potentially please be sure this fix is acceptable.  I ended up just copying my changes into the GitHub browser... please again double check this will work please test for me if you can find time as I know it is something that needs tested.

Thank you everyone for help @bdukes deserves some credit here for the help thank again.

I was also thinking of changing out the comments which I had added you can edit as you please for any changes you desire.

And also in the same file some obsolete items could be resolved I could potentially help with that as well if desired.

Thank you!

2020-09-08 14:06 UTC, bdukes approved these changes
Do we want to add the `web.config` values on upgrade, or just rely on the fallback?  Otherwise this looks good (with a few suggestions)

2020-09-08 14:06 UTC, bdukes commented on DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
> +        private readonly string disableMobileViewCookieName = ConfigurationManager.AppSettings[name: "DisableMobileViewSiteCookieName"] ?? "dnn_NoMobile";
Let's make these `static` so you don't need a `FriendlyUrlController` instance to use them
```suggestion
        private static readonly string MobileViewSiteCookieName = ConfigurationManager.AppSettings[name: "MobileViewSiteCookieName"] ?? "dnn_IsMobile";
        private static readonly string DisableMobileViewCookieName = ConfigurationManager.AppSettings[name: "DisableMobileViewSiteCookieName"] ?? "dnn_NoMobile";

```

2020-09-08 14:06 UTC, bdukes commented on DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
> +        // gets a portal friendly url settings
```suggestion
        // <summary>Gets the Friendly URL Settings for the given portal.</summary>
```

2020-09-08 14:06 UTC, bdukes commented on DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
> +            var cn = new FriendlyUrlController();
```suggestion
```

2020-09-08 14:06 UTC, bdukes commented on DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
> +                    HttpCookie viewMobileCookie = response.Cookies[cn.mobileViewSiteCookieName];
```suggestion
                    HttpCookie viewMobileCookie = response.Cookies[MobileViewSiteCookieName];
```

2020-09-08 14:06 UTC, bdukes commented on DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
> +                                response.Cookies.Add(new HttpCookie(cn.mobileViewSiteCookieName, isMobile.ToString())
```suggestion
                                response.Cookies.Add(new HttpCookie(MobileViewSiteCookieName, isMobile.ToString())
```

2020-09-08 14:06 UTC, bdukes commented on DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
> +                    var cookie = new HttpCookie(cn.disableMobileViewCookieName)
```suggestion
                    var cookie = new HttpCookie(DisableMobileViewCookieName)

```

2020-09-08 14:06 UTC, bdukes commented on DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
> +                    var cookie = request.Cookies[cn.disableMobileViewCookieName];
```suggestion
                    var cookie = request.Cookies[DisableMobileViewCookieName];

```

2020-09-08 14:06 UTC, bdukes commented on DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
> +                        cookie = new HttpCookie(cn.disableMobileViewCookieName)
```suggestion
                        cookie = new HttpCookie(DisableMobileViewCookieName)

```

2020-09-08 14:06 UTC, bdukes commented on DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
> +                var cookie = request.Cookies[cn.disableMobileViewCookieName];
```suggestion
                var cookie = request.Cookies[DisableMobileViewCookieName];

```

2020-09-08 14:06 UTC, bdukes commented on DNN Platform/Website/development.config
> +    <!-- set cookie name for mobile -->
```suggestion
```

2020-09-08 14:06 UTC, bdukes commented on DNN Platform/Website/release.config
> +    <!-- set cookie name for mobile -->
```suggestion
```

2020-09-08 14:38 UTC, mitchelsellers requested changes
@bdukes I assume we should add a configuration merge file into this as well for upgrades?

2020-09-08 15:01 UTC, bdukes commented
We can, but if we're setting it to the same value as the default, I don't know that it really matters.

2020-09-08 15:08 UTC, thabaum commented
setting it or not it can be added later by someone interested in changing it.

I wanted to use static, with a `const` the suggestion was to change to `readonly` to allow variable.  I rather have done it your way @bdukes thanks for showing it was ok to do so.

I like the changes and committed them as shown.  Thank you.

2020-09-08 15:46 UTC, thabaum commented
> @bdukes I assume we should add a configuration merge file into this as well for upgrades?

I was curious about this part as well, and where or how this would be done for future reference.

2020-09-08 16:22 UTC, mitchelsellers commented
@bdukes I would tend to agree, my only concern/thought is about the discoverability of the property.  Without the configuration value there and no UI reference to it, I don't know that existing sites would know it is an option.

2020-09-08 16:38 UTC, thabaum commented
I agree with the discoverability being an issue which is why I also wish to document the added feature.

May I ask which file would be able to manage update changes like this?  Just out of curiosity even if we do not add anything to it for this PR.

2020-09-08 17:43 UTC, bdukes commented
You would add a versioned `.config` file with an XML Merge document.  You can see an example from the Token Provider PR #3969, [`09.08.00.config`](https://github.com/dnnsoftware/Dnn.Platform/pull/3969/files#diff-518cc92a834687e51bd4ec125085e75b).

2020-09-08 19:05 UTC, thabaum commented
That should make it work please adjust things as needed I am hoping I did this correctly.

Thank you.

2020-09-08 20:28 UTC, mitchelsellers approved these changes

2020-09-08 21:40 UTC, thabaum commented
Thought I was done but do you think I should also add the keys to `appSettings` in the Test App.config file as well?

2020-09-08 22:10 UTC, bdukes approved these changes
This all looks good to me.  I don't think it makes a difference to set it in the tests' config file.

2020-09-08 22:10 UTC, bdukes commented on DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
> +            var cn = new FriendlyUrlController();
This shouldn't be needed anymore, right?
```suggestion
```

2020-09-08 22:10 UTC, bdukes commented on DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
> +
Don't need this extra blank line
```suggestion
```

2020-09-10 01:21 UTC, valadas approved these changes
Looks good to me

2020-09-10 01:21 UTC, merged