Cleanup Upgrade/Installer Code
dnnsoftware/Dnn.Platform pull request #4119
Opened 2020-09-22 06:09 UTC by mitchelsellers

Resolves #4118 

This PR removes all unused code that is used to complete upgrades prior to 7.4.2 and earlier.  

## Background
A bit of important background, in addition to what was initially noted in the Issue.

DNN Platform, upon install starts by applying an initial script, then it "Upgrades" the application from one version to another until it is fully updated.  Currently, the [DotNetNuke.Install.Config](https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Website/Install/DotNetNuke.install.config.resources) file starts this process at 08.00.04 and upgrades from there.  For extra safety I only removed upgrade steps to 7.4.2.

As a reminder, if you follow the upgrade path, the removal of these elements will have NO impact as the upgrade to 7.4.2 alone would have processed these items.  Given this, I do NOT believe that this a breaking change.

## Included Cleanups

Included in this cleanup is removal of the following items:

* Internal elements fully contained inside of the Upgrade.cs
* Removal of XML Configuraiton Merge elements no longer needed
* Documentation of a few API's that are no longer used by the platform, however, were exposed publicly in error

2020-09-22 14:04 UTC, bdukes approved these changes

2020-09-22 14:10 UTC, mitchelsellers commented on DNN Platform/Library/Services/Installer/LegacyUtil.cs
> -        public static void ProcessLegacyModules()
Not exactly, ore of a difference in approach after seeing all of the internal usages.  The more I think about it, the more I'm in favor of just removing the others.  

Yes they are public, but they are internal utilities for the installer and unused.

2020-09-23 03:56 UTC, valadas requested changes

2020-09-23 03:56 UTC, valadas commented on DNN Platform/Library/Common/Initialize.cs
>                      // Try and Upgrade to Current Framewok
Looks good to me except this little stray comment that is no longer relevant

```suggestion
                    Globals.DatabaseEngineVersion = GetDatabaseEngineVersion();
```

2020-09-23 04:03 UTC, valadas commented on DNN Platform/Library/Services/Installer/LegacyUtil.cs
> -        public static void ProcessLegacyModules()
I agree with @mitchelsellers here, although this was public, it really is something used by Dnn modules install/upgrades and it relates more to legacy manifests than developers actually calling this API. I vote for removing it for that reason.

2020-09-23 04:03 UTC, valadas approved these changes
Looks good to me

2020-09-23 05:11 UTC, valadas commented
/azp run

2020-09-23 13:19 UTC, merged