do not cache output if page is redirected
dnnsoftware/Dnn.Platform pull request #4279
Opened 2020-11-05 12:03 UTC by tauqeer-haider

Fixes #4278 

## Summary

Prevented caching of the page output if the page is redirected.

2020-11-05 14:13 UTC, bdukes requested changes
Thanks for this!  I think I would prefer this check to be a level higher, in [`OutputCacheModule`](https://github.com/dnnsoftware/Dnn.Platform/blob/a0793aab185567505c7d7b70548b5e5596d69601/DNN%20Platform/HttpModules/OutputCaching/OutputCacheModule.cs#L247-L257), which already has references to the context and response, and already does a check on user agent.

2020-11-05 15:20 UTC, bdukes approved these changes
Thanks!  Let's move the check up higher, but otherwise this looks good to me 👍🏻

2020-11-05 15:20 UTC, bdukes commented on DNN Platform/HttpModules/OutputCaching/OutputCacheModule.cs
>              if (!HttpContext.Current.Request.Browser.Crawler)
```suggestion
            var request = HttpContext.CurrentRequest;
            var isRedirect = response.StatusCode == (int)HttpStatusCode.Redirect;
            if (!request.Browser.Crawler && !isRedirect)
```

2020-11-05 15:20 UTC, bdukes commented on DNN Platform/HttpModules/OutputCaching/OutputCacheModule.cs
> +                    HttpContext.Current.Response.StatusCode != Convert.ToInt32(HttpStatusCode.Redirect))
```suggestion
                if (responseFilter != null)
```

2020-11-05 15:21 UTC, bdukes commented on DNN Platform/HttpModules/OutputCaching/OutputCacheModule.cs
> +            var request = HttpContext.CurrentRequest;
```suggestion
            var request = HttpContext.Current.Request;
```

2020-11-06 19:29 UTC, valadas approved these changes
Looks good to me, thanks.

2020-11-06 19:30 UTC, valadas commented
Oops, there is this build error though:

```
"D:\a\1\s\DNN_Platform.sln" (Rebuild target) (1) ->
       "D:\a\1\s\DNN Platform\DotNetNuke.Web\DotNetNuke.Web.csproj.metaproj" (Rebuild target) (6) ->
       "D:\a\1\s\DNN Platform\HttpModules\DotNetNuke.HttpModules.csproj" (Rebuild target) (19) ->
       (CoreCompile target) -> 
         OutputCaching\OutputCacheModule.cs(251,30): error CS0103: The name 'response' does not exist in the current context [D:\a\1\s\DNN Platform\HttpModules\DotNetNuke.HttpModules.csproj]
```

2020-11-06 19:32 UTC, valadas requested changes

2020-11-06 19:32 UTC, valadas commented on DNN Platform/HttpModules/OutputCaching/OutputCacheModule.cs
> +            var isRedirect = response.StatusCode == (int)HttpStatusCode.Redirect;
response does not exist here (build failed).

2020-11-08 18:47 UTC, valadas approved these changes
Awesome, thanks

2020-11-08 18:48 UTC, merged