Issue-4353 - Connectors use black and white icons when they're in disconnected state which is against branding rules
dnnsoftware/Dnn.Platform pull request #4354
Opened 2020-12-09 19:03 UTC by berkarslan-xo

Fixes #4353

## Summary

This simple CSS change will ensure that the colorful icon will be used both when the Connectors are connected and disconnected.

Demo: https://drive.google.com/file/d/1N_O47unL7H5UV0X4zZKEN8yvs9YnOmi6/view?usp=sharing

2020-12-09 19:09 UTC, bdukes commented
https://github.com/dnnsoftware/Dnn.Platform/blob/6b98a4064471151eba62712a4100b36b10f53f72/DNN%20Platform/Connectors/Azure/Images/Azure.png also needs to be adjusted to remove the black-and-white version, right?

2020-12-09 19:21 UTC, berkarslan-xo commented
> https://github.com/dnnsoftware/Dnn.Platform/blob/6b98a4064471151eba62712a4100b36b10f53f72/DNN%20Platform/Connectors/Azure/Images/Azure.png also needs to be adjusted to remove the black-and-white version, right?

It will work fine even with the current icons since the background-position will take -37px. However, if you suggest to remove the black and white parts from all of the icons, the CSS file and all of the images (both in Platform and Evoq) should be updated of course.

2020-12-09 22:14 UTC, mitchelsellers requested changes
I am going to go ahead and say that I do NOT approve of this.  This appears to be a specific change for Evoq, and I would agree with the comment on the issue that grayscale for disconnected is an industry standard as well.

2020-12-10 23:56 UTC, david-poindexter reviewed
It is common practice to show greyscale for inactive and colored for active.  This does not violate the brand guidelines since there is a greyscale version in the brand identity guide document at http://www.dnnsoftware.com/portals/0/sitefiles/dnn_corp_brand_guidelines.pdf.  Thanks.

2020-12-11 16:28 UTC, mitchelsellers commented
Per the feedback and standards of UI/UX feedback, we are closing this issue at this time.  

If there is a specific claim from a vendor regarding this pattern it should be discussed and addressed at that time.

2020-12-11 16:28 UTC, closed without merging