Clean up warnings in CKEditorProvider
dnnsoftware/Dnn.Platform pull request #4374
Opened 2020-12-16 21:34 UTC by bdukes

26 obsolete warnings remain

2020-12-16 21:37 UTC, mitchelsellers approved these changes

2020-12-17 00:07 UTC, valadas requested changes
Left a couple of comments here and there, otherwise it looks good to me.

2020-12-17 00:07 UTC, valadas commented on DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
> +                /*if (roleToolbar.RoleId.Equals(this.portalSettings.AdministratorRoleId) && HttpContext.Current.Request.IsAuthenticated)
Should we remove commented out code ?

2020-12-17 00:07 UTC, valadas commented on DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
> +            ////}
Should we remove commented out code ?

2020-12-17 14:30 UTC, bdukes commented on DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
> +                /*if (roleToolbar.RoleId.Equals(this.portalSettings.AdministratorRoleId) && HttpContext.Current.Request.IsAuthenticated)
```suggestion
```

2020-12-17 14:31 UTC, bdukes commented on DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
> +            ////}
```suggestion
            var postBackScript = string.Format(
                @" if (CKEDITOR && CKEDITOR.instances && CKEDITOR.instances.{0}) {{ CKEDITOR.instances.{0}.updateElement();  if (typeof Page_IsValid !== 'undefined' && Page_IsValid) CKEDITOR.instances.{0}.destroy(); }}",
                editorFixedId);

            this.RegisterOnSubmitStatement(
                this.GetType(), string.Format("CKEditor_OnAjaxSubmit_{0}", editorFixedId), postBackScript);
```

2020-12-17 14:37 UTC, bdukes commented on DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
> +                /*if (roleToolbar.RoleId.Equals(this.portalSettings.AdministratorRoleId) && HttpContext.Current.Request.IsAuthenticated)
This has been removed, thanks!

2020-12-17 14:37 UTC, bdukes commented on DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
> +            ////}
This has been removed, thanks!

2020-12-17 17:13 UTC, bdukes commented
FYI, I have already rebased #4383 on these changes locally, the conflicts are already taken case of

2020-12-21 21:51 UTC, donker approved these changes

2020-12-21 21:54 UTC, merged