Enable warnings as errors for JWT
dnnsoftware/Dnn.Platform pull request #4375
Opened 2020-12-16 21:36 UTC by bdukes

2020-12-16 21:37 UTC, mitchelsellers approved these changes

2020-12-16 22:55 UTC, valadas requested changes
I would prefer a solution where we don't override deprecated usages, so we actually give the good example specially if we enable "Treat warning as errors". As discussed in slack I gonna try and do another PR to add the functionality so 3rd parties actually have a way and not be forced to implement stuff we declared deprecated.

2020-12-17 14:43 UTC, bdukes commented
Just to be clear, if we added a feature to replace `PortalSettings.PortalAlias`, that would need to go in 9.9.0.  Do we want to hold this PR until then, or do we want to merge this as-is, and then adjust it when the better solution is available?

2020-12-17 18:01 UTC, valadas approved these changes
Yeah, I am ok merging this as it is.
I am just not in love with both bypassing the warning and enabling "Treat warnings as errors", but yeah, we can improve that soon I guess and then remove this

2020-12-21 22:00 UTC, merged