Improve SSL approach
dnnsoftware/Dnn.Platform pull request #4892
Opened 2021-11-02 18:48 UTC by donker

This PR aims to do the following:

1. Simplify the UI that manages the SSL settings for a site
2. Introduce a simplified "make this site SSL" setting that doesn't require any other tweaks and ensures all content can only be accessed through https.

The overarching goal is to improve security. Users can get lost in the various settings and mistakes are easily made.

## Implementation

The changes are as follows:

1. Introduction of a new portal setting SSLSetup. This setting is an enum which (for now) consists of "Off", "On" and "Advanced". This setting replaces the old SSLEnabled setting.
2. The SSL settings page in the Personabar now starts with a dropdown that sets the above setting. The other bits of the UI are shown dependent on the settings.
3. Where necessary the code is adjusted to ensure that a site set to SSLSetup "On" always assumes URLs must be SSL.

2021-11-12 20:56 UTC, bdukes commented
I've updated the base for this PR to the new `release/9.11.0` branch, it is ready to merge once approved

2021-11-12 20:56 UTC, bdukes approved these changes

2021-11-14 04:11 UTC, mitchelsellers requested changes
Looks good, and great behavior changes I think this will help.  I did make one suggestion for naming/consistency.

2021-11-14 04:11 UTC, mitchelsellers commented on Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/Ssl/PortalStats.cs
> +        public int NrTabs { get; set; }
I believe that this field, and the following 2 should be either renamed to "NumberOfTabs" or "TabCount" to provide clear, non-shorted variable names.

2021-11-14 04:27 UTC, valadas approved these changes
Other than the mentioned suggestions and a double-check from @bdukes on potential breaking changes, this looks great to me. Nice one!

2021-11-15 14:25 UTC, bdukes commented on DNN Platform/Library/Entities/Portals/PortalSettings.cs
> +        public bool SSLEnabled => this.SSLSetup != Abstractions.Security.SiteSslSetup.Off;
I don't think this should cause an issue. We'd had an issue with `PortalId` delegating to `PortalID` like this, but it was the casing issue, not the property usage.

2022-01-04 20:57 UTC, valadas approved these changes
Thank you sir.

2022-01-04 21:56 UTC, mitchelsellers approved these changes

2022-01-04 21:56 UTC, merged

2022-01-04 22:07 UTC, WillStrohl commented
I'm late to the party, but I have two questions... 

1. Shouldn't the primary underlying `SSLEnabled` property in the API be marked for deprecation and removed later?  
2. Shouldn't this setting and the web service be superuser-only?  An administrator may not have the necessary knowledge/expertise to know what happens turning this feature on and off.