Fix for issue #5047.
dnnsoftware/Dnn.Platform pull request #5054
Opened 2022-03-20 15:00 UTC by Andy9999

Fix for issue #5047.

This will allow to optionally remove the rel attribute from privacy and terms links. Default is still "rel=nofollow" but it could now either be changed or removed entirely from the ascx file.

Unfortunately the asp.net control doesn't have a rel attribute, so we have to add it ourselves.

Added Rel attribute to Privacy and Terms class and added rel="nofollow" to privacy.ascx and terms.ascx skin file.

## Summary

2022-03-20 20:19 UTC, valadas requested changes
Unless I am misunderstanding something, this will not make it configurable, it will always be rel="nofollow" this way...

2022-03-20 20:20 UTC, valadas commented
Also, we use the PR titles mainly to write the release notes, so I changed the title to explain what the PR does.

2022-03-20 21:50 UTC, Andy9999 commented
> Unless I am misunderstanding something, this will not make it configurable, it will always be rel="nofollow" this way...

Yes, correct. This is the current behavior. The difference is that it could now be removed from the ascx file if desired, without recompiling.

2022-03-20 22:03 UTC, Andy9999 commented
> Also, we use the PR titles mainly to write the release notes, so I changed the title to explain what the PR does.

OK. Thank you, will do it properly the next time.

2022-03-21 00:33 UTC, valadas commented
>Yes, correct. This is the current behavior. The difference is that it could now be removed from the ascx file if desired, without recompiling.

But it's not a best practice to edit core files anyway, I was thinking it could be made an option in a parameter like you did but it looks to me like the parameter is not being used this way.

2022-03-21 08:42 UTC, Andy9999 commented
> > Yes, correct. This is the current behavior. The difference is that it could now be removed from the ascx file if desired, without recompiling.
> 
> But it's not a best practice to edit core files anyway, I was thinking it could be made an option in a parameter like you did but it looks to me like the parameter is not being used this way.

The reason why rel ended up in the cs file in the first place is because Microsoft's asp hyperlink doesn't have a rel attribute, so it cannot be set from the markup usually. Attempting to set it from the ascx produces an error. I found this workaround on stackexchange for example.

The (in my opinion) better alternative was to add the missing attribute to the class(es). It works. I tested it yesterday. With the change in place, it will still render the rel as nofollow. When removing it from the ascx t will disappear entirely. It looks a bit strange because the classes member Rel is not used anywhere, but it will still get rendered (magically).

2022-03-21 13:36 UTC, bdukes reviewed
As @valadas said, our goal would be to allow theme authors to override this without making any changes to core files. I think this approach with my edits should work. Thanks!

2022-03-21 13:36 UTC, bdukes commented on DNN Platform/Website/admin/Skins/Privacy.ascx.cs
> +        public string Rel { get; set; }
```suggestion
        public string Rel { get; set; } = "nofollow"
```

2022-03-21 13:36 UTC, bdukes commented on DNN Platform/Website/admin/Skins/Privacy.ascx.cs
>                  this.hypPrivacy.NavigateUrl = this.PortalSettings.PrivacyTabId == Null.NullInteger ? this._navigationManager.NavigateURL(this.PortalSettings.ActiveTab.TabID, "Privacy") : this._naviga
```suggestion
                this.hypPrivacy.NavigateUrl = this.PortalSettings.PrivacyTabId == Null.NullInteger ? this._navigationManager.NavigateURL(this.PortalSettings.ActiveTab.TabID, "Privacy") : this._navigationManager.NavigateURL(this.PortalSettings.PrivacyTabId);
                this.hypPrivacy.Attribute["rel"] = this.Rel;
```

2022-03-21 13:36 UTC, bdukes commented on DNN Platform/Website/admin/Skins/Terms.ascx.cs
> +        public string Rel { get; set; }
```suggestion
        public string Rel { get; set; } = "nofollow"
```

2022-03-21 13:36 UTC, bdukes commented on DNN Platform/Website/admin/Skins/Terms.ascx.cs
>                  this.hypTerms.NavigateUrl = this.PortalSettings.TermsTabId == Null.NullInteger ? this._navigationManager.NavigateURL(this.PortalSettings.ActiveTab.TabID, "Terms") : this._navigationMa
```suggestion
                this.hypTerms.NavigateUrl = this.PortalSettings.TermsTabId == Null.NullInteger ? this._navigationManager.NavigateURL(this.PortalSettings.ActiveTab.TabID, "Terms") : this._navigationManager.NavigateURL(this.PortalSettings.TermsTabId);
                this.hypTerms.Attributes["rel"] = this.Rel;
```

2022-03-21 13:36 UTC, bdukes commented on DNN Platform/Website/admin/Skins/privacy.ascx
> +<asp:hyperlink id="hypPrivacy" runat="server" cssclass="SkinObject" enableviewstate="False" rel="nofollow"></asp:hyperlink>
```suggestion
<asp:hyperlink id="hypPrivacy" runat="server" cssclass="SkinObject" enableviewstate="False"></asp:hyperlink>
```

2022-03-21 13:36 UTC, bdukes commented on DNN Platform/Website/admin/Skins/terms.ascx
> +<asp:hyperlink id="hypTerms" runat="server" cssclass="SkinObject" enableviewstate="False" rel="nofollow"></asp:hyperlink>
```suggestion
<asp:hyperlink id="hypTerms" runat="server" cssclass="SkinObject" enableviewstate="False"></asp:hyperlink>
```

2022-03-21 17:29 UTC, valadas commented
The way I see it, the login one has it hardcoded in the view and it cannot be customized (without editing the core files, which we do not recommend).

2022-03-21 17:33 UTC, Andy9999 commented
OK. Interesting to see the devs perspective. Am more in the user perspective here. :)

I made a couple of such changes and merge them during each update. From my perspective this is totally acceptable. And of course I prefer changing some (core) markup files over having to recompile DNN.

2022-03-21 17:36 UTC, Andy9999 commented
> > Rel is now initialized twice, once from the rel attribute in the HTML markup and once from the code behind file. But the markup will win
> 
> If you accept the suggestions @bdukes made above by clicking the "Commit suggestion" on each, then it will have a default and theme developers will have a setting on the skin object to override that default. The class will change it at runtime accordingly thus no longer needing to modify the core ascx file, it will be simply a theme implementation that does not get overridden upon upgrades.

Oh....wasn't aware of that.

2022-03-21 17:43 UTC, Andy9999 commented
> @Andy9999 the intention of the Platform is that you should not have any changes which get overwritten by an upgrade. Any changes that you want which would be overwritten by an upgrade should use an extension point which DNN does not overwrite (or a new extension point if one doesn't exist, e.g. adding a `Rel` property to the `Privacy` theme object control)
> 
> ASP.NET web controls can have their `Attributes` collection set via the `ascx` markup if an attribute in the markup doesn't match an existing property on the control's class. So the `asp:HyperLink` control doesn't need any special support to set `rel="nofollow"`, it just renders it directly as an attribute on the rendered `<a>` tag. We want the `Privacy` control to allow a theme developer to set `<dnn:Privacy runat="server" rel=""/>` (which sets the `Rel` property defined on the class), which then sets the `"rel"` attribute on the `asp:HyperLink`, resulting in `rel=""` being rendered).

Thanks....maybe the exception I saw, when adding rel to the markup without that change, was because the code behind attempted to add an attribute that already exists in the markup/skin. I didn't investigate the crash any further.

2022-03-21 17:46 UTC, Andy9999 commented
Seems I also missed out that Login.Ascx or User.Ascx use hyperlink directly whereas Privacy and Terms have their own classes.

2022-03-21 17:52 UTC, Andy9999 commented
To sum it up and if I got your feedback right, you would prefer to have a setting somewhere, e.g. in PortalSettings to turn it on and off?

Then....no core files would have to be touched. Right?

2022-03-21 17:58 UTC, bdukes commented on DNN Platform/Website/admin/Skins/Privacy.ascx.cs
> +            }
```suggestion
                this.hypPrivacy.Attributes["rel"] = this.Rel;
            }
```

2022-03-21 17:58 UTC, bdukes commented on DNN Platform/Website/admin/Skins/Terms.ascx.cs
> +            }
```suggestion
                this.hypPrivacy.Attributes["rel"] = this.Rel;
            }
```

2022-03-21 18:00 UTC, bdukes commented
I don't think we would need anything added to `PortalSettings`. Wherever the privacy and terms controls are used (i.e. in the theme) is the place where `rel` could be set, which wouldn't require any core changes, just theme changes.

2022-03-21 18:00 UTC, bdukes approved these changes
This looks good to me now, thanks!

2022-03-21 18:30 UTC, Andy9999 commented
Shall I add the semicolons?

2022-03-21 18:30 UTC, valadas approved these changes
Awesome, thanks guys, this now also looks good to me, merging.

2022-03-21 18:32 UTC, Andy9999 commented
I love to contribute by adding semicolons. ;) That's easy and I do it the whole day anyways.

2022-03-21 18:50 UTC, valadas commented
@bdukes I am a bit confused about the build error, how do we find the problem nowadays, is the only way with the binlog with the viewer ?

2022-03-21 18:55 UTC, Andy9999 commented
My last update (semicolons) doesn't have the Green verified thingy [https://github.com/dnnsoftware/Dnn.Platform/pull/5054/commits](https://github.com/dnnsoftware/Dnn.Platform/pull/5054/commits)

2022-03-21 18:57 UTC, bdukes commented
@valadas 😕it should be posting build errors as errors in DevOps, but apparently that isn't working, so viewing the binlog is the only way to get more details

2022-03-21 18:59 UTC, bdukes commented
Sorry, my typo. Fix building now.

2022-03-21 19:01 UTC, Andy9999 commented
Very agile!

2022-03-21 19:02 UTC, Andy9999 commented
Would probably be easier if we were in the same room or in a chat somehow.

2022-03-21 19:34 UTC, merged

2022-03-21 20:14 UTC, bdukes commented
If you really don't want `rel=""` you can set the value to `null`:

```
<dnn:Terms runat="server" ID="TheTerms" />

<script runat="server">
protected override void OnLoad(EventArgs e)
{
  TheTerms.Rel = null;
}
</script>
```

2022-03-21 20:15 UTC, Andy9999 commented
I think the whole change could now be undone, because that was possible before. :)

2022-03-21 20:19 UTC, bdukes commented
We can add a `if (!string.IsNullOrWhiteSpace(this.Rel) { this.hypTerms["rel"] = this.Rel; }` wrapper around the defining of the attribute if you want to make a follow-up contribution.

It is now possible to change or remove the `rel="nofollow"` attribute from the link without making any changes to the core files, but only adjusting your theme. This is a valuable contribution, otherwise we wouldn't have accepted it. I'm sorry if there was miscommunication on what our goals were.

2022-03-21 20:20 UTC, Andy9999 commented
> We can add a `if (!string.IsNullOrWhiteSpace(this.Rel) { this.hypTerms["rel"] = this.Rel; }` wrapper around the defining of the attribute if you want to make a follow-up contribution.
> 
> It is now possible to change or remove the `rel="nofollow"` attribute from the link without making any changes to the core files, but only adjusting your theme. This is a valuable contribution, otherwise we wouldn't have accepted it. I'm sorry if there was miscommunication on what our goals were.

I guess this won't help due to the order of execution.

1) Rel is initialized to nofollow
2) OnLoad is execute and add the attribute to the hyperlink (nofollow)
3) Then Rel is set to whatever is in the markup code without any effect

2022-03-21 20:22 UTC, bdukes commented
Are you trying to set the `Rel` property on the `<dnn:Terms>` control in your theme file?

2022-03-21 20:23 UTC, Andy9999 commented
No, maybe that's the culprit! I did it in the Terms.Ascx file, the file you told me to not change. :)

2022-03-21 20:24 UTC, Andy9999 commented
I slowly start to understand what we are doing here.

2022-03-21 20:34 UTC, Andy9999 commented
Wow! Works perfectly if including your last suggestion. Now it matches the issue title again. Can I still submit it or is it too late now?

2022-03-21 20:41 UTC, Andy9999 commented
Just submitted the change and will change the skin files. The way it should be done! Thanks Daniel and Brian.

2022-03-21 20:57 UTC, Andy9999 commented
New issue??

2022-03-21 21:02 UTC, bdukes commented
No, you can associate it with the same issue. Thanks!

2022-03-21 21:03 UTC, bdukes commented
You will have to open a new PR, but it'll be associated to the same issue #5047

2022-03-21 21:10 UTC, Andy9999 commented
Like this? https://github.com/dnnsoftware/Dnn.Platform/pull/5057

2022-03-21 21:15 UTC, bdukes commented
That works 👍🏻

The one thing to do differently is instead of include #5047 in the PR title, in the description include "Fixes #5047" (or "For #5047" if it's not a complete fix). This will let GitHub automatically create a link between the PR and the issue.

2022-03-21 21:33 UTC, Andy9999 commented
Thanks.

2022-03-21 23:39 UTC, Andy9999 commented
Got it deployed on the production server now along with the other issue (search result category localization). Looks great now! I find nothing to complain about.

Somehow (with my limited understanding) it did not seem to be a big difference if rel would be changed in the Terms/Privacy markup files or the skin. I have to watch out when updating the skin as well and merge changes with the ones we did. We use the awesome EasyDNN themes. But I clearly see the advantage now. :)

2022-03-21 23:46 UTC, Andy9999 commented
One final question.....would it make a big difference to initialize the new Rel attribute from the markup instead of having it in the code behind file? And...would this raise more awareness for the skin developers that there is now such an attribute that could be customized? Or would they consult the code behind anyways or get that info from the release notes?

Just a question for future issue of similar nature.

2022-03-22 13:20 UTC, bdukes commented
`<dnn:Terms runat="server" ID="TheTerms" Rel="" />` is the way you would initialize the property via markup. There isn't a place to do that initialization in the Terms control itself, it has to be in the codebehind.

We probably do need to document this new property by creating a page on https://docs.dnncommunity.org/content/tutorials/themes/theme-objects/index.html#breadcrumb-theme-object-example (e.g. like [the breadcrumb docs](https://docs.dnncommunity.org/content/tutorials/themes/theme-objects/breadcrumb/index.html))

2022-03-22 15:05 UTC, bdukes commented
Doc comments are always appreciated :-)

2022-03-22 15:43 UTC, valadas commented
@Andy9999  documentation about theme objects is also welcome if you have the time https://docs.dnncommunity.org/content/tutorials/themes/theme-objects/index.html