Update Upgrade Process to remove Telerik (WIP) (Continue to #5099)
dnnsoftware/Dnn.Platform pull request #5166
Opened 2022-06-24 07:25 UTC by armaganpekatik

## Summary

Please see #5099

2022-07-06 19:26 UTC, bdukes requested changes

2022-07-06 19:26 UTC, bdukes commented on DNN Platform/Modules/TelerikRemoval/TelerikRemoval.dnn
> +                    <upgradeVersionsList>upgrade</upgradeVersionsList>
We only want to run the upgrade behavior on install. This should allow us to remove the change to `09.11.00.SqlDataProvider`.

```suggestion
                    <upgradeVersionsList>install</upgradeVersionsList>
```

2022-07-06 19:26 UTC, bdukes commented on DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.11.00.SqlDataProvider
> +GO
This seems like it's going to cause problems. We're assuming this in place to trick DNN into running the "upgrade" logic, but the other change I suggested should let us avoid needing to trick DNN at all.

```suggestion
```

2022-07-25 21:36 UTC, bdukes approved these changes

2022-07-29 08:28 UTC, donker commented
Closing this and continuing in PR #5212

2022-07-29 08:28 UTC, closed without merging