Allows opening resource manager folders with double-click
dnnsoftware/Dnn.Platform pull request #5352
Opened 2022-10-23 20:53 UTC by valadas

Closes #5276

2022-10-23 21:37 UTC, david-poindexter requested changes
Looks great - thanks @valadas - just one minor clean up item.

2022-10-23 21:37 UTC, david-poindexter commented on DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list-item/dnn-rm-folder-list-item.tsx
> +      console.log(e);
```suggestion
```

2022-10-23 22:20 UTC, valadas commented on DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list-item/dnn-rm-folder-list-item.tsx
> +      console.log(e);
Good catch

2022-10-23 22:43 UTC, david-poindexter approved these changes

2022-10-24 14:29 UTC, bdukes approved these changes
LGTM

2022-10-24 14:30 UTC, merged