Fix for #5360: WebP format adeded to logo
dnnsoftware/Dnn.Platform pull request #5365
Opened 2022-11-01 16:58 UTC by uzmannazari

Fixes #5360

## Summary

The WebP format was added to the list of allowed files for uploading the logo in the site settings, which was mentioned in post 
I just added the image/webp format to the list of allowed files for logo upload in the site settings

2022-11-01 16:58 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=5365) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=5365) before we can accept your contribution.<br/><br/>:x: uzmannazari [sign now](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=5365)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dnnsoftware/Dnn.Platform?pullRequest=5365) it.</sub>

2022-11-01 18:58 UTC, valadas requested changes
If we do allow this in the list, we also have to make it so the upload succeeds by adding it to the allowed extensions and in the web.config so that it does not fail. This is only the UI part that allows selecting such file type but in the default config that upload would ultimately fail.

2022-11-04 23:59 UTC, uzmannazari commented
@bdukes is everything ok with this commits or should I do something else?

2022-11-07 14:10 UTC, valadas commented
@uzmannazari did you read my change request, this will fail unless that extension is in the allowed files for images, so we can't accept this PR the way it is now or it will provide a bad UX to users thinking they can do something they can't

2022-11-08 20:18 UTC, valadas commented
![image](https://user-images.githubusercontent.com/6371568/200666464-d894412c-83b7-43d1-9ec0-be51d6a25dfb.png)

This is a screenshot of the images whitelist we discussed today in a meeting. This list needs to be updated on top of @mitchelsellers other comment, just though to drop the screenshot here to help understand

2022-11-08 20:18 UTC, mitchelsellers commented
For this to be merged, we must ensure that the following areas are updated.

* Global Whitelist for allowed file types - Ensure that it doesn't get duplicated
* Only Images whitelist (Site Settings -> Site Behavior -> More) - Same as above
* Web.config must be updated for clean installations to include the proper MIME type
* Web.config must be updated for upgrade installations to include the proper MIME type, which needs to avoid a collision.

2022-11-08 20:30 UTC, valadas requested changes
The documented requests need to be handled for this to get merged

2023-04-11 19:36 UTC, mitchelsellers commented
Changes were requested to this PR that have not yet been addressed, we are going to close this PR at this time.

Feel free to correct the requested items and you can re-open or re-submit it.

2023-04-11 19:36 UTC, closed without merging