Fix 'Add Missing Languages' when parent page only has some languages enabled
dnnsoftware/Dnn.Platform pull request #5404
Opened 2022-11-23 01:52 UTC by mwigley-trilogy

## Summary
The previous code was throwing a null ref exception in CreateLocalizedCopyInternal when trying to copy languages that didn't exist in the parent page.  Instead we should skip them.

Also added a warning to the UI to make it clear to users why all their languages weren't added for partially localized parent pages.

Fixes https://github.com/dnnsoftware/Dnn.Platform/issues/5403

2022-11-23 02:40 UTC, mwigley-trilogy commented on Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
> +                bool allLanguagesAdded = this.tabController.AddMissingLanguages(this.PortalId, pageId);
Ah that's a pain.  Yeah I think using an exception would be a bit too hacky. I can add a new method.

Or can just go back to not showing a warning at all (would still at least fix the crash) - it was a bit of a nice-to-have anyway.

2022-11-23 02:58 UTC, mwigley-trilogy commented on Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
> +                bool allLanguagesAdded = this.tabController.AddMissingLanguages(this.PortalId, pageId);
Have moved it to AddMissingLanguagesWithWarnings. Let me know if that's not enough.

2022-11-23 03:15 UTC, valadas requested changes
Another little change request

2022-11-23 20:05 UTC, valadas commented on DNN Platform/Library/Entities/Tabs/ITabController.cs
>          void AddMissingLanguages(int portalId, int tabId);
Thank you

2022-11-23 20:07 UTC, valadas approved these changes
Looks ok to me now

2022-11-23 20:08 UTC, valadas commented
I build failure looks like a fluke to me, let me re-fire it to rule that out...

2022-11-23 20:08 UTC, valadas commented
/azp run

2022-11-24 00:03 UTC, valadas commented
/azp run

2022-11-29 20:11 UTC, bdukes approved these changes
LGTM

2022-11-29 20:11 UTC, merged