Fix monaco editor not being loaded when switching between css console and sql console
dnnsoftware/Dnn.Platform pull request #5453
Opened 2022-12-21 23:01 UTC by mwigley-trilogy

Fixes #5452

## Summary

Fix monaco editor not being loaded when switching between css console and sql console - see #5452

2022-12-21 23:05 UTC, bdukes commented on Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/SqlConsole.html
> +            <div id="monaco-editor-css"></div>
```suggestion
            <div id="monaco-editor-sql"></div>
```

2022-12-21 23:05 UTC, bdukes commented on Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/scripts/SqlConsole.js
> +      var monacoEditor = sqlConsole.create(document.getElementById("monaco-editor-css"), {
```suggestion
      var monacoEditor = sqlConsole.create(document.getElementById("monaco-editor-sql"), {

```

2022-12-21 23:05 UTC, bdukes approved these changes
thanks!

2022-12-21 23:11 UTC, david-poindexter requested changes
Great catch @mwigley-trilogy - I'll approve when @bdukes change suggestions are committed.

2022-12-21 23:19 UTC, mwigley-trilogy commented
Ah whoops, I meant to change the css files. that's what I get for making changes in a hurry! anyway changing the sql one instead is fine. It'll just mean more of the internal ignite integration tests are broken hah. But at least this change will fix some of them too!

2022-12-27 20:20 UTC, david-poindexter approved these changes

2022-12-27 20:20 UTC, merged