Small change to resource manager settings
dnnsoftware/Dnn.Platform pull request #5558
Opened 2023-02-26 08:25 UTC by MaiklT

Fixes #4212

## Summary

Added keys to resource file, and code to retrieve localized values.

2023-02-26 08:37 UTC, david-poindexter requested changes
@MaiklT you may want to check this one a bit closer.  It looks like perhaps a copy/paste gone wrong with the RESX file.  :)

2023-02-26 23:24 UTC, valadas approved these changes
Looks good to me now

2023-02-26 23:34 UTC, valadas commented
I mean, it looked fine but Localization is not existing in context here, probably need to test this one better

2023-03-14 19:46 UTC, bdukes commented on DNN Platform/Modules/ResourceManager/Settings.ascx.cs
> +                var displayTypes = displayTypesValues.Select(t => new ListItem(Localization.GetString(string.Format("ModuleModes.{0}", Utils.GetEnumDescription(t)), LocalResourceFile), ((int)t).ToStr
```suggestion
                var displayTypes = displayTypesValues.Select(t => new ListItem(Localization.GetString($"ModuleModes.{Utils.GetEnumDescription(t)}.Text", LocalResourceFile), ((int)t).ToString())).ToArray();
```

2023-04-11 19:35 UTC, mitchelsellers commented
Changes were requested to this PR that have not yet been addressed, we are going to close this PR at this time.

Feel free to correct the requested items and you can re-open or re-submit it.

2023-04-11 19:35 UTC, closed without merging