Implement new default theme
dnnsoftware/Dnn.Platform pull request #5893
Opened 2023-12-22 22:24 UTC by david-poindexter

## Summary
This PR implements the new default theme for DNN 10.  In addition to this PR, there will be additional PRs to handle updates to the `Default` and `Blank` templates.  There will also be updates to DNN 10 `default.css` that will warrant additional PR(s) to the theme to remove additional CSS overhead.  Some other small refinements will also warrant additional PRs.  ;-)

Highlights:
* Minimal package dependencies (will ultimately be all devDependencies once `normalize.css` can be removed)
* Build system using `rollup.js` (https://rollupjs.org/)
* Browsersync for better local developer experience (https://browsersync.io/)
* No CSS Framework
* SCSS compilation for minified CSS output
* TypeScript source with transpiled minified JavaScript output
* Preloading of fonts
* No jQuery if popups are disabled (i.e., the SEARCH skin object is not used)

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/4568451/509c5c9a-9104-4a7e-be64-44ba341a4064)

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/4568451/866f8941-90dd-4c36-8ae5-991ee3bbd75b)

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/4568451/21bcc132-b415-4018-a456-c6acf3def34b)

2023-12-23 01:20 UTC, valadas requested changes
Just a couple minor things

2023-12-23 01:24 UTC, david-poindexter commented on DNN Platform/Skins/Aperture/partials/_footer.ascx
> +<dnn:Login runat="server" id="dnnHiddenLogin" CssClass="hiddenLogin" />
Oh yeah, probably not.  I'll remove this now.  Thanks for pointing this out!

2023-12-23 01:27 UTC, david-poindexter commented on DNN Platform/Skins/Aperture/partials/_footer.ascx
> +<dnn:Login runat="server" id="dnnHiddenLogin" CssClass="hiddenLogin" />
@valadas this has now been resolved in https://github.com/dnnsoftware/Dnn.Platform/pull/5893/commits/831d4396b4e94854e9adca1fba907204311d829e

2023-12-23 01:29 UTC, david-poindexter commented on DNN Platform/Skins/Aperture/Aperture.sln
Agreed - this has been removed in https://github.com/dnnsoftware/Dnn.Platform/pull/5893/commits/d36a87d7680125c2d1eec8c4df847e198378a3b0

2023-12-23 01:30 UTC, valadas approved these changes
Awesome!

2023-12-23 02:56 UTC, david-poindexter commented
I have no clue why this build is failing in Azure, as it is working fine locally.  @valadas and I both made a few guesses, but none of them worked.  The error is so obscure, we have no clue where it is coming from.  @bdukes any ideas/clues?

2023-12-23 23:26 UTC, david-poindexter commented
Yay - the build issue is now resolved - for all those who sent prayers up for me, thank you!!!

<img src="https://media0.giphy.com/media/Ih6f3JK5YkZCY9azoQ/giphy-downsized-medium.gif"/>

2023-12-24 01:15 UTC, mitchelsellers approved these changes

2023-12-24 16:28 UTC, merged