Fix #6004: get role for current site
dnnsoftware/Dnn.Platform pull request #6005
Opened 2024-03-26 18:07 UTC by anurag-singh-df

Fixes https://github.com/dnnsoftware/Dnn.Platform/issues/6004

## Summary
Role is now updated when user moves from one portal to another.

## Test
[DEMO - Site_Role_Test]( https://drive.google.com/file/d/1b3WyisKtB8KYw3Hh4bsoTk3Ws_UaYh_-/view?usp=sharing)

### Test 1
Created two sites [portal1](http://engage-9-13-3-184-308.qa.evoqondemand.com/portal1/) and [portal2](http://engage-9-13-3-184-308.qa.evoqondemand.com/portal2/):
![image](https://github.com/trilogy-group/eng-maintenance/assets/38633444/7d589174-c1e1-4686-875d-3543c3e667e5)

Created a new user as `user1`
![image](https://github.com/trilogy-group/eng-maintenance/assets/38633444/2f479385-0cfb-421a-98a5-186d30c7f895)

`Content Editor` permission granted to `user1` in `portal1` as below:
![image](https://github.com/trilogy-group/eng-maintenance/assets/38633444/a9841f51-41a8-4850-bd41-3c4139779fbd)

`Content Editor` permission `NOT` granted to `user1` in `portal2` as below:
![image](https://github.com/trilogy-group/eng-maintenance/assets/38633444/52debb8c-f458-4c50-8b3a-0ce8e5541b21)

Logged in to `portal1` as `user1` and can see edit option:
![image](https://github.com/trilogy-group/eng-maintenance/assets/38633444/6b8d88b3-d975-4800-b619-e775c39794e5)

Logged in to `portal2` as `user1` (using active session from portal1) and `NO` edit option:
![image](https://github.com/trilogy-group/eng-maintenance/assets/38633444/0aa8c598-8f42-41d4-b14d-8df3c93ac0dd)

THIS IS WORKING AS EXPECTED !!!!

### Test 2
Did a new/fresh login in to `portal2` as `user1` and `NO` edit option:
![image](https://github.com/trilogy-group/eng-maintenance/assets/38633444/0aa8c598-8f42-41d4-b14d-8df3c93ac0dd)

Logged in to `portal1` as `user1` (using active session from portal2) and and can see edit option:
![image](https://github.com/trilogy-group/eng-maintenance/assets/38633444/6b8d88b3-d975-4800-b619-e775c39794e5)

THIS IS WORKING AS EXPECTED !!!!

2024-03-26 18:10 UTC, anurag-singh-df commented
@microsoft-github-policy-service agree company="Trilogy"

2024-03-26 19:36 UTC, aaiordac requested changes

2024-03-26 19:36 UTC, aaiordac commented on DNN Platform/Library/Entities/Users/UserController.cs
> +            if (user != null && user.PortalID != portalId)
I think this logic should go into the `FixMemberPortalId()` function, which is called multiple times in this class. Fixing this inline here, like this, allows the other usages of the function to stay broken (and the user object to have outdated roles.)

2024-03-26 19:36 UTC, aaiordac commented on DNN Platform/Library/Entities/Users/UserController.cs
> +            if (user != null && user.PortalID != portalId)
No automated tests for the new logic

2024-03-27 03:06 UTC, zyhfish commented
This is already handled by #5976 .

2024-03-27 16:40 UTC, anurag-singh-df commented
@zyhfish 
Thanks for pointing this out. I was checking for a fix like this in [issues](https://github.com/dnnsoftware/Dnn.Platform/issues) and I didn't notice any issue logged so I didn't look at pull requests.
The issue is resolved by https://github.com/dnnsoftware/Dnn.Platform/pull/5976/files and so closing this.

2024-03-27 16:40 UTC, closed without merging