Imports css-variables into Persona Bar main styles
dnnsoftware/Dnn.Platform pull request #6279
Opened 2024-12-30 03:22 UTC by valadas

This replaces hardcoded values in the PersonaBar main styles to use the dnn css-variables which allows matching branding.

- The previous way to provide a PersonaBar theme still works, so if implementors want their own style to stay unchanged no matter what portal the admin UI is accessed from, that can still work by using actual values instead of the css variables.
- This does not yet include the common components and the modules themselves, I'll do that in other PRs.

Out of box style (very similar to original)
![image](https://github.com/user-attachments/assets/413fe7b9-3b5d-41fd-9c98-a1257035519c)

With a different color theme (to match the site under it):
![image](https://github.com/user-attachments/assets/0d9f0200-e306-423c-94a0-cc6f06dec7b0)

2024-12-31 06:19 UTC, david-poindexter requested changes
@valadas  I attempted to start correcting some of these in the browser as suggestions, but it was just bombing out the browser, so maybe you could update the others in your branch and push a new commit now that you see what went wrong?

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        line-height: 28px
```suggestion
        line-height: 28px;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        white-space: nowrap
```suggestion
        white-space: nowrap;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        opacity: 0
```suggestion
        opacity: 0;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        height: 100%
```suggestion
        height: 100%;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        top: 0
```suggestion
        top: 0;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        overflow: hidden
```suggestion
        overflow: hidden;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        transform-origin: 50% 20%
```suggestion
        transform-origin: 50% 20%;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        background: transparent
```suggestion
        background: transparent;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    box-sizing: border-box
```suggestion
    box-sizing: border-box;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    pointer-events: none
```suggestion
    pointer-events: none;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    border-radius: 0 !important
```suggestion
    border-radius: 0 !important;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    float: right
```suggestion
    float: right;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    margin-top: 12px
```suggestion
    margin-top: 12px;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    cursor: pointer
```suggestion
    cursor: pointer;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    margin-top: 36px
```suggestion
    margin-top: 36px;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    margin-top: 11px
```suggestion
    margin-top: 11px;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    margin: 0
```suggestion
    margin: 0;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    margin-top: 0
```suggestion
    margin-top: 0;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +            line-height: 24px
```suggestion
            line-height: 24px;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +            padding-bottom: 0
```suggestion
            padding-bottom: 0;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +            word-break: break-all
```suggestion
            word-break: break-all;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +            text-decoration: none
```suggestion
            text-decoration: none;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +            word-break: break-all
```suggestion
            word-break: break-all;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +            padding-left: .5em
```suggestion
            padding-left: .5em;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        padding-bottom: 6px
```suggestion
        padding-bottom: 6px;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    list-style: none
```suggestion
    list-style: none;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        visibility: visible
```suggestion
        visibility: visible;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        visibility: hidden
```suggestion
        visibility: hidden;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        display: block !important
```suggestion
        display: block !important;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +        font-family: pb_semibold,Arial
```suggestion
        font-family: pb_semibold, Arial;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    cursor: default
```suggestion
    cursor: default;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    height: 5px
```suggestion
    height: 5px;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    cursor: pointer
```suggestion
    cursor: pointer;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    height: 11px
```suggestion
    height: 11px;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    display: none
```suggestion
    display: none;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    left: 400px !important
```suggestion
    left: 400px !important;
```

2024-12-31 06:19 UTC, david-poindexter commented on Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
> +    display: none
```suggestion
    display: none;
```

2024-12-31 17:22 UTC, valadas commented
@david-poindexter I ran the file through prettier to bring back all those semi-colons which also made some great enhancements for readability on long rgba funcitons using long variables names, etc. See https://github.com/dnnsoftware/Dnn.Platform/pull/6279/commits/3f82fc6e0358d182a193ee7c2072f1cd7cfed936 for only this diff, or just let me know what you think with the current state. I also removed 2 usages of color-mix which is a bit flagship for browsers.

2024-12-31 17:29 UTC, david-poindexter commented
> @david-poindexter I ran the file through prettier to bring back all those semi-colons which also made some great enhancements for readability on long rgba funcitons using long variables names, etc. See [3f82fc6](https://github.com/dnnsoftware/Dnn.Platform/commit/3f82fc6e0358d182a193ee7c2072f1cd7cfed936) for only this diff, or just let me know what you think with the current state. I also removed 2 usages of color-mix which is a bit flagship for browsers.

Oh yeah - this looks MUCH better!

2024-12-31 17:44 UTC, david-poindexter approved these changes
Awesome - thanks @valadas 🎉

2025-01-04 21:28 UTC, merged

2025-01-04 22:19 UTC, valadas commented
Soo, when rebasing I accidently pushed this commit directly to release/10.0.0 by accident.

@dnnsoftware/approvers if there are any concerns with this PR, I can fix that in https://github.com/dnnsoftware/Dnn.Platform/pull/6291

Or I can revert the commit if you guys prefer and resubmit this PR.

2025-01-04 22:21 UTC, david-poindexter commented
> Soo, when rebasing I accidently pushed this commit directly to release/10.0.0 by accident.
> 
> @dnnsoftware/approvers if there are any concerns with this PR, I can fix that in #6291
> 
> Or I can revert the commit if you guys prefer and resubmit this PR.

Thanks for the heads up.  I think this PR is just fine though and most likely nobody would have issues with it.  Let me know if you need my help with anything should someone want this to be reverted.